name: ESLint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: blmage/eslint-action@1.1.0
        with:
          files: src/
          maxWarnings: 0
